### PR TITLE
Overhauled the Installer

### PR DESCRIPTION
**Pull request by ghost**
Please refer to the commit message. Hope these changes help. It _should_ all work correctly; let me know if you have any issues with the changes, should you choose to try/use them.

### CODE REVIEW

**Comment by ghost** [comment]
I've tested this (the line below) just now, but it refuses to resolve the link, which I'm assuming is what you want; to get the true name of the script executable, rather than whatever someone might call it via link.

```
SDN="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd -P)"
```

Out of curiosity, why are you accounting for the script being a link?

Hope my changing this sort of thing to `SDN=${0##*/}` didn't break any link setups.

**Comment by michaeltd** [comment]
Hey there o/

bash -v 4+ being an actual requirement (BASHpass kinda gives it away) it's safe to say that a posixly correct install script is nowhere near my list of priorities.

Readability on the other hand being a highly subjective topic* isn't an actual problem (or requirement).
For example install script's last three commands (dbcreate, encrypt and launch) are not meant
to be readable or posix compliant, they are meant to succeed or fail as a unit leaving the minimum amount of mess in case anything goes south for the user to troubleshoot according to the last error message he/she encounters. That is actual, meaningful error messages!!!

*eg. I've seen bash case statements that will make your eyeballs bleed not to mention there is no way to keep/maintain/support them under any kind of auto indent system! 

So to wrap things up (and to not waste your good efforts) I'll ask you to submit a new PR with the readme.org changes as is and adding an extra check clause in the install script checking for [bash version](https://github.com/michaeltd/bashpass/blob/master/bashpass#L116) but without the helper function (of the main script) honoring install script's conventions .

That's all! 
Cheers, 
have fun! 
o/

**Comment by michaeltd** [comment]
> Out of curiosity, why are you accounting for the script being a link?

Besides better safe than sorry...

The idea is that no matter how you invoke this script, it should work under it's own original directory.
It's good practice security wise and functionally as it'll* check for a mutex lock, It should be able to look in the right place for it.

[Here's my take on said test](https://imgur.com/Vcog3iq).

*the main script checks for mutex but applies to the install script as well as resulting pgp files should reside in that directory also.

**Comment by ghost** [comment]
Nice one! I'll adjust changes when I get a chance. Thanks for the feedback and sorry if I wasted your time.

Also, the Bash thing made me laugh a lot, although I POSIX-ed the installer just to keep it simple and lightweight, but since Bash is required for it too, I'll change it back.

**Comment by michaeltd** [comment]
There's no such thing as wasted time.

**Comment by ghost** [comment]
~~When you say "helper function", are you referring to `Err()`?~~

Nevermind, I see what you mean. You're referring to:

Selectshot_2020-02-28_22:46:23

And now I understand why you wanted to keep the error messages consistent. Maybe I should've started with `bashpass`. lol

**Comment by michaeltd** [comment]
> When you say "helper function", are you referring to `Err()`?

I'm referring to the main scripts ```display_feedback``` helper function I've [linked](https://github.com/michaeltd/bashpass/blob/master/bashpass#L116) for you.

**Comment by ghost** [comment]
Thanks!

**Pull request closed without merging**
